### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ar-jan** [unipv-larl/udeasy#4]
When installing udeasy on Ubuntu 20.04, running it results in:

> Error loading Python lib '/tmp/_MEI7ELsFB/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEI7ELsFB/libpython3.10.so.1.0)

It seems this can easily happen with pyinstaller binaries. Providing build instructions for Linux users would be a good addition, since both GCC and Python version on the user's system need to match that of the binary (I think).

**Comment by bavagliladri** [comment]
Thank you for sharing this issue. UDeasy can also be run from terminal.

To run UDeasy from the terminal, you can follow these steps:
1. Clone the UDeasy repository.
2. Install the required packages using the requirements file provided.
3. Navigate to the `UDeasy` directory where `home.py` is located.
4. Run the following command to launch UDeasy:

```sh
python3 home.py
```

This will launch UDeasy in the terminal.

In addition to running UDeasy from the terminal, you can also build a binary using tools such as PyInstaller, py2exe, or cxFreeze. Building the executable from your machine should solve the issue of the mismatch that you described. This will allow you to have UDeasy as a standalone executable file.

**Comment by ar-jan** [comment]
Yep, I had gotten it running. The requirements file is missing though, I found the dependencies in the GitHub workflow file instead.

**Comment by bavagliladri** [comment]
I just added the requirements file
